FROM node:14-alpine3.12 as builder

# set working directory
WORKDIR /home/app

# copy everything including package.json and yarn.lock
COPY . .

ENV NODE_ENV=production

ARG REACT_APP_PROXY_SERVER=$REACT_APP_PROXY_SERVER

ENV REACT_APP_PROXY_SERVER=$REACT_APP_PROXY_SERVER

COPY package.json .
COPY yarn.lock .
RUN yarn --frozen-lockfile --no-cache --production
RUN yarn run build


FROM node:14-alpine3.12 as prod


WORKDIR /home/app
COPY --from=builder /home/app/build ./

RUN yarn global add serve
# heroku require port to be specify on run time.
CMD serve -l $PORT




